// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsBL4IslhZOrt2gOLx1qhjMgjQWGEkM-4',
    appId: '1:523743085334:web:836b5061dbbff4d2dcc637',
    messagingSenderId: '523743085334',
    projectId: 'shoppingapp-9a27d',
    authDomain: 'shoppingapp-9a27d.firebaseapp.com',
    storageBucket: 'shoppingapp-9a27d.appspot.com',
    measurementId: 'G-QY8H75VEYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4vVuiMZaVemeqzWZJhHMzAZos3FJ1HUw',
    appId: '1:523743085334:android:59d5cabb80f4dd6ddcc637',
    messagingSenderId: '523743085334',
    projectId: 'shoppingapp-9a27d',
    storageBucket: 'shoppingapp-9a27d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA61Rsv7UjZiHz5CoCT4DqP10WPFAdxKgo',
    appId: '1:523743085334:ios:7db278abf4655a74dcc637',
    messagingSenderId: '523743085334',
    projectId: 'shoppingapp-9a27d',
    storageBucket: 'shoppingapp-9a27d.appspot.com',
    iosClientId: '523743085334-7du6s00selms0mvq0a5ua6qcc289f1dc.apps.googleusercontent.com',
    iosBundleId: 'com.TheBlackPL.shoppingApp',
  );
}
