name: shopping_app
description: An Flutter app to shop with payment integration

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_storage:
  cloud_firestore: ^4.7.1
  auto_route: 7.2.0
  file_picker: ^5.3.1
  injectable: ^2.1.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  dio: ^5.1.0
  quickalert: ^1.0.1
  hive:
  hive_flutter:
  salem_package:
    git: https://github.com/SalemZakkar/SalemPackage.git
  json_annotation: ^4.8.0
  flashy_tab_bar2: ^0.0.6
  carousel_slider: ^4.2.1
  flutter_native_image: ^0.0.6+1
  image_cropper: ^4.0.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_gen_runner:
  injectable_generator:
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0

  auto_route_generator: ^7.1.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: cairo
      fonts:
        - asset: assets/font/cairo.ttf
  assets:
    - assets/images/

flutter_gen:
  output: lib/presentation/core/source/
